### ISSUE TITLE
Search whole JSON object and highlight

### ISSUE THREAD

**Issue by tarim** [CarstenWickner/react-jsonschema-inspector#2]
Hi There,

I try to use your component, but, it looks like not support search from the whole JSON object.  Does any suggestion, please?

**Comment by CarstenWickner** [comment]
Hi,

Can you please provide a specific example to reproduce:
- What props do you provide?
- What search term do you enter and what result do you expect?

**Comment by tarim** [comment]
Hi @CarstenWickner,

Currently, I am using #react-json-view, and it is very good, but, it does not support any search and highlight. So, I am trying to switch your component. But, I don't know does it support to view and allow to search JSON object or not. If it does, how to use it, please?

Thank you,

**Comment by CarstenWickner** [comment]
Hi @tarim,

generally: yes, the react-jsonschema-inspector does support some search functionality.
That being said, there is **a big difference between the two components**:
- The "react-json-view" (as far as I can tell) is designed to show one particular JSON object or array.
- The "react-jsonschema-inspector" is meant to display a JSON Schema definition and allows searching in that, e.g. for something mentioned in a "title" or "description" attribute in the JSON Schema.

To show this on an example:
- You would use a component like the "react-json-view" to show a particular JSON instance, e.g.
```json
{
    "firstName": "Harry",
    "lastName": "Dresden",
    "homeTown: "Chicago"
}
```
- In the "react-jsonschema-inspector" you would show the generic JSON Schema definition for that:
```json
{
    "Person": {
        "description": "A human being",
        "properties": {
            "firstName: {
                "title": "First Name",
                "description": "Given name (including any middle names)",
                "type": "string",
                "minLength": 1,
                "maxLength": 1000
            },
            "lastName: {
                "title": "Last Name",
                "description": "Family name",
                "type": "string",
                "minLength": 1,
                "maxLength": 1000
            },
            "homeTown: {
                "title": "Home Town",
                "description": "City where they spend most of their time",
                "type": "string",
                "examples": [ "Chicago", "Edinburgh", "Paris", "Berlin", "Auckland" ]
            },
            "required": [ "firstName", "lastName" ]
        }
    }
}
```

----

**If displaying a JSON Schema (not a particular JSON object/array!), then you've come to the right place.** 😉
To enable the search, you'll simply have to provide the `searchOptions` prop with either a non-empty `fields` array or a custom `filterBy` function, e.g.
```javascript
<Inspector
    schemas={{
        "Person": {
            "description": "A human being",
            ...
    }}
    searchOptions={{
        fields: ["title", "description"]
    }}
/>
```
If you then entered the search term "city", it would highlight both the "Person" entry in the first column as well as the "homeTown" entry in the second column (once you select "Person".

**Comment by CarstenWickner** [comment]
I'm closing this now as I believe you are looking for another kind of component: one that does show a JSON object instance and not its schema.
